### PR TITLE
JS related improvements

### PR DESCRIPTION
**Pull request by nairihar**
- Better testing
- Continuous integration for JS
- `.npmignore` added

### CODE REVIEW

**Comment by nairihar** [comment]
@ashvardanian I think it's important to review the `.npmignore` file. I'm sure there are many more things that we can ignore, which will make the npm package smaller and lightweight.

**Comment by ashvardanian** [comment]
Thank you, @nairihar! All looks good, but can you please drop the CI part, we already have [one](https://github.com/unum-cloud/usearch/blob/be501724db187954804f13f20e0a8a1aacf2a9f8/.github/workflows/prerelease.yml#L142) .

**Comment by nairihar** [comment]
@ashvardanian Sure, I didn't notice the JS CI.
I've removed CI-related changes.

**Pull request merged**
