### PR TITLE
Invalid: C must work with synthetic data #207

### PR DESCRIPTION
**Pull request by mgevor**

### CODE REVIEW

**Comment by mgevor** [comment]
Also, fixed memory leaks.

**Comment by ashvardanian** [comment]
Would it be a good idea to add this test to GitHub CI, at least on Ubuntu?

I am also wondering if we can make cpp-check, mentioned in `compilation.md`, or some other C++ linter part of the pipeline? That may be a stricter way of checking standard compliance than `-pedantic` builds.

**Comment by mgevor** [comment]
In fact, we are testing the C interface when running GoLang tests, which are based on the C interface.
But anyway, this is not explicit so that I will add it

**Comment by mgevor** [comment]
Added a new test case for #222

**Review by ashvardanian — APPROVED** [review]

**Pull request merged**
