### PR TITLE
Add: Usearch build and test GitHub action

### PR DESCRIPTION
**Pull request by gurgenyegoryan**

### CODE REVIEW

**Review by ashvardanian — CHANGES_REQUESTED** [review]
Can you rename commits from `Add` to `Make`? Otherwise, it triggers a minor release just for those CI actions. Can you also do rigorous ASAN checks?

**Comment by ashvardanian** [comment]
@gurgenyegoryan I believe ASAN should also be enabled for GCC builds, as a common alternative.

**Comment by gurgenyegoryan** [comment]
> @gurgenyegoryan I believe ASAN should also be enabled for GCC builds, as a common alternative.

@ashvardanian Yes, it's enabled for GCC too.

**Pull request merged**
