### PR TITLE
fix: esm bug in jest

### PR DESCRIPTION
**Pull request by eryue0220**
This pr is to solve #418

### CODE REVIEW

**Review by ashvardanian — APPROVED** [review]

**Comment by ashvardanian** [comment]
Can this break compatibility with other JS environments?

**Comment by eryue0220** [comment]
> Can this break compatibility with other JS environments?

Oh, you're right. It will break esm compatibility 🤣, but I forgot it. Because nodejs requires the esm module must have a `.mjs` extension or  add `"type": "module"` in `package.json`. 

I think I need to upgrade the build tool to `vite`, because `tsc` couldn't configure the target file extension.

**Comment by eryue0220** [comment]
Sorry, I didn't notice that `dist-package-esm.json` has done what I said before. Now it won't break compatibility with other JS environments.

**Comment by ashvardanian** [comment]
@eryue0220 did you push any changes? Are the module exports supposed to be deleted?

**Comment by eryue0220** [comment]
> @eryue0220 did you push any changes? Are the module exports supposed to be deleted?

No any other changes. Yes it's supposed to be deleted.

**Pull request merged**
