### PR TITLE
Add: Swift & Obj-C bindings for filteredSearch

### PR DESCRIPTION
**Pull request by vardhan**
Added a couple of tests in Swift to test both functions.

Tested with `swift build && swift test -v`

Issue: #470

### CODE REVIEW

**Comment by vardhan** [comment]
gentle ping @ashvardanian 🙏

**Comment by vardhan** [comment]
Thanks!  I fixed the issues that CI raised.

However, when I try to build (`swift build`) locally (or from a clean `origin/main-dev`), i get:
```
In file included from /Users/vardhan/github/usearch/objc/USearchObjective.mm:5:
In file included from /Users/vardhan/github/usearch/include/usearch/index_dense.hpp:12:
/Users/vardhan/github/usearch/include/usearch/index_plugins.hpp:1123:20: error: redefinition of 'cast_gt<signed char, __fp16>'
template <> struct cast_gt<i8_t, bf16_t> : public cast_from_i8_gt<bf16_t> {};
                   ^~~~~~~~~~~~~~~~~~~~~
```

though it doesnt look like CI is hitting this issue.   Note that if I checkout an older commit (tag v2.14.0), I don't see any failures.

**Comment by ashvardanian** [comment]
That looks like a mistake in the core implementation, that may even be coming from SimSIMD type definitions, where bf16 maps to fp16. That shouldn't happen.

**Comment by vardhan** [comment]
> That looks like a mistake in the core implementation, that may even be coming from SimSIMD type definitions, where bf16 maps to fp16. That shouldn't happen.

This was the error I mentioned earlier -- It doesn't seem like it's related to this PR though.  Please let me know if CI throws any more issues (I don't have the ability to run it from my fork)

In case it matters, I'm building on an `Apple Macbook w/ M3` (so arm64), Sonoma 14.6, and XCode 15.4

**Comment by ashvardanian** [comment]
Thank you, @vardhan! Merged 😉

**Pull request merged**
