### PR TITLE
USearch v3: Text Indexes, Faster Views, Cleaner API and Docker

### PR DESCRIPTION
**Pull request by ashvardanian**
The v3 release of USearch is bringing several new features, and provides an excellent opportunity to refactor existing ones!

- [x] Uniform naming across bindings.
- [x] Making `tqdm` and `ucall` dependencies optional.
- [ ] Co-locating vectors and graph data on disk.
- [ ] Better compaction before serialization to make searches over `view` faster.
- [ ] `TextIndex`, TF-IDF, and Levenshtein distances from [StringZilla](https://github.com/ashvardanian/stringzilla).
- [ ] Docker image with a [UCall](https://github.com/unum-cloud/ucall)-based REST API.
- [ ] Tooling for sampling/pooling a hybrid embedding from long documents embedded in chunks.
- [x] Support batch-capable distance metrics and masked loads from [SimSIMD](https://github.com/ashvardanian/simsimd).

Candidates:

- [ ] External retrievers and node-level serialization. @Ngalstyan4
- [x] Batch-add and batch-search interfaces for C, Rust. @var77

### CODE REVIEW

**Comment by var77** [comment]
Thank you for your work! It will also be great to have a batch add functionality in Rust bindings.

**Comment by monatis** [comment]
Thanks for the awesome work!

> - [ ] Docker image with a [UCall](https://github.com/unum-cloud/ucall)

Will this support multiple indexes / collections? Like endpoints for creating a collection (vector index), listing available collections, searching in the given collection etc. all in a single Docker container.

**Comment by ashvardanian** [comment]
@monatis, yes, that’s the plan 🤗

**Comment by monatis** [comment]
Super news. It's already great for embedded use but a dockerized service mode can cater for new use cases.

**Comment by ashvardanian** [comment]
I've released [SimSIMD v2](https://github.com/ashvardanian/SimSIMD/releases/tag/v2.0.0), which will be included in USearch v3. It brings several performance and versatility improvements and may soon feature Intel AMX support and more bitwise metrics.

**Comment by philippemnoel** [comment]
Thank you for your work! Do you have an estimate on when USearch v3 will be ready?

**Comment by ashvardanian** [comment]
Thank you, @philippemnoel! I plan to release it before the end of October.

Here is the progress so far:

- A better compaction plan for on-disk views. cc @al13n321.
- Masked-loads support in [SimSIMD](https://github.com/ashvardanian/simsimd) shipped this weekend.
- Levenstein distance present in [StringZilla](https://github.com/ashvardanian/stringzilla) will be released with the next major release, potentially tomorrow.

Once we fix the build issues in UCall CI, all the pieces will fall into place, and the release will be easier to prepare. Feel free to help there 🤗

**Comment by aehlke** [comment]
Would be amazing to prioritize langchainJS integration

**Comment by ashvardanian** [comment]
@aehlke, I believe [USearch is already available in LangChainJS](https://js.langchain.com/docs/integrations/vectorstores/usearch).

**Comment by aehlke** [comment]
Ah I meant for this new text search functionality - maybe there's nothing to be added on their side.

**Comment by monatis** [comment]
Hi @ashvardanian it seems that this pr is merged without V3 changes. I just wanted to ask if  you are still planning to release them and if you have a new ETA?

I was thinking of using USearch in an upcoming product but a stable file format might be important.

Not necessarily related to V3, but are you planning to support incrementally adding vectors in memmaped files, or what is the recommended procedure to add new vectors after the initial upload?

**Comment by aehlke** [comment]
Is there an update on text index and related updates originally planned? Thanks

**Comment by ashvardanian** [comment]
Hello @monatis and @aehlke,

I hope you're both doing well. The past few weeks have been incredibly busy as we wrapped up our year-long projects. You might have come across some of these initiatives:

- [Publishing 28 Billion Molecule Embeddings with AWS](https://ashvardanian.com/posts/usearch-molecules/)
- [Scaling USearch Vector Search Engine with Gcore on Intel's Sapphire Rapids CPUs](https://www.unum.cloud/blog/2023-11-07-scaling-vector-search-with-intel)

Collaborating with large organizations has its challenges, particularly in terms of pace. This has required us to adjust our timelines slightly. Nonetheless, progress on v3 is steady, along with other updates and integrations, including contributions to [SciPy](https://github.com/scipy/scipy/issues/19454) and a potential integration with Sklearn.

Beating existing solutions in vector and text search, clustering, dimension reduction, and external memory access is doable. But achieving that in one package under 10,000 lines of maintainable code compatible with every OS and hardware architecture is very tricky. I want to make sure the design persists for years, so I'm not rushing to make sure we get it right.

Thank you for your continued support and patience! 🤗

**Comment by aehlke** [comment]
I appreciate the context, best of luck!

**Pull request merged**
